export default function Head() {
  return (
    <head>
      <title>Shop</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta
        name="description"
        content="Generated by create next app and Made with 🔥 by Ethem KIZILYER"
      />
      <link rel="icon" href="/favicon.ico" />
    </head>
  );
}
